### ISSUE TITLE
Eliminar Console.log 

### ISSUE THREAD

**Issue by Nidev-lab** [Luci6611/HOXTON-FRONT#13]
Buenas! como va? chicos al ingresar con un usuario aparece una lista de object donde se muestra los datos del usuario.

![image](https://user-images.githubusercontent.com/53904695/193868371-3821764d-9cfd-4629-b06d-938bff5fbed3.png)

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by NicolasMoralesDev** [comment]
listo
