### ISSUE TITLE
error en consola

### ISSUE THREAD

**Issue by Nidev-lab** [Luci6611/HOXTON-FRONT#14]
Buenas! chicos les dejo otra issue donde aparece error en consola que deberian resolver..

![image](https://user-images.githubusercontent.com/53904695/193868819-4ab81f04-2919-4a91-b903-50ff5fb6270b.png)

tambien aqui ..

![image](https://user-images.githubusercontent.com/53904695/193869090-e251d047-e309-442b-8251-6c521389c3c3.png)

en la segunda imagen todavia se ve que sigue un console.log activo donde cuenta sgundos si no me equivoco, tambien tienen que solucionar eso.

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by NicolasMoralesDev** [comment]
ok solucionado
