### ISSUE TITLE
Error al intentar registrar un usuario

### ISSUE THREAD

**Issue by Nidev-lab** [Luci6611/HOXTON-FRONT#17]
Buenas! en este caso al intentar registrar un usuario note que se puede ejecutar la peticion de registro de usuario sin tener todos los campos obligatorios. Esto es una vulnerabilidad importante , ya que cualquier atacante podria ejecutar ciclos infinitos hasta voltear el servidor en el que esta alojada nuestra App.

posible solucion: validar los campos obligatrorios antes de generar la peticion

![image](https://user-images.githubusercontent.com/53904695/194789479-f0ff6da3-cf32-4439-b332-148a034d8bec.png)

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by NicolasMoralesDev** [comment]
solucionado!
